import {
  SiDocker,
  SiFigma,
  SiJavascript,
  SiLinux,
  SiMeteor,
  SiMinio,
  SiMongodb,
  SiNginx,
  SiNodedotjs,
  SiPostgresql,
  SiReact,
  SiSqlite,
  SiSvelte,
  SiTraefikproxy
} from "react-icons/si";
import {
  TbApi,
  TbBolt,
  TbBriefcase,
  TbBulb,
  TbBuildingBroadcastTower,
  TbBuildingStore,
  TbChartDots,
  TbCircleDot,
  TbCircuitGround,
  TbCloudCog,
  TbComponents,
  TbCube,
  TbDatabaseCog,
  TbDeviceDesktop,
  TbDeviceDesktopAnalytics,
  TbFileText,
  TbGitBranch,
  TbHierarchy3,
  TbLayoutDashboard,
  TbLock,
  TbLogs,
  TbMusic,
  TbNetwork,
  TbPlugConnected,
  TbPuzzle,
  TbRocket,
  TbServer,
  TbShieldLock,
  TbSpider,
  TbStack2,
  TbTimeline,
  TbUsb,
  TbUserCog,
  TbUsersGroup
} from "react-icons/tb";

export const skillIconMap = {
  JavaScript: SiJavascript,
  "Node.js": SiNodedotjs,
  React: SiReact,
  Svelte: SiSvelte,
  SvelteKit: SiSvelte,
  "Meteor.js": SiMeteor,
  "REST APIs": TbApi,
  "Realtime Systems": TbBolt,
  "Component UI": TbComponents,
  "Frontend Architecture": TbLayoutDashboard,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  SQLite: SiSqlite,
  "Job Queues": TbStack2,
  "Multi-tenant": TbUsersGroup,
  "Auth Flows": TbShieldLock,
  Integrations: TbPlugConnected,
  Scraping: TbSpider,
  "CRM Workflows": TbDatabaseCog,
  "CMS Integrations": TbCloudCog,
  Docker: SiDocker,
  "Docker Compose": SiDocker,
  Coolify: TbCloudCog,
  "Linux Server": SiLinux,
  Nginx: SiNginx,
  Traefik: SiTraefikproxy,
  "SSL / DNS": TbLock,
  "CI/CD": TbGitBranch,
  "S3 / MinIO": SiMinio,
  "VPS Ops": TbServer,
  "Log Debugging": TbLogs,
  "Product Thinking": TbBulb,
  "System Architecture": TbHierarchy3,
  "Figma to Product": SiFigma,
  "MVP Planning": TbRocket,
  "SaaS Structure": TbBuildingStore,
  "User Workflows": TbUserCog,
  "Technical Decisions": TbChartDots,
  "Problem Solving": TbPuzzle,
  "Client Delivery": TbBriefcase,
  Documentation: TbFileText,
  DMX512: TbDeviceDesktop,
  "Art-Net": TbNetwork,
  "USB-DMX": TbUsb,
  RS485: TbCircuitGround,
  "Stage Workflows": TbBuildingBroadcastTower,
  "Cue Planning": TbTimeline,
  "Sound & Lighting": TbMusic,
  "3D Enclosures": TbCube,
  "Hardware Testing": TbDeviceDesktopAnalytics,
  "Live Event Systems": TbUsersGroup
};

export function getSkillIcon(skillName) {
  return skillIconMap[skillName] || TbCircleDot;
}
